name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  command:
    description: 'Test command'
    default: 'npm run test'
  GITHUB_TOKEN:
    description: 'Github token of the repository'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
